name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.12.29
    - uses: lablabs/setup-tflint@v1.0.2
    - uses: lablabs/setup-terraform-docs@v1.0.4
      name: Setup Terraform docs
      with:
        terraform_docs_version: v0.9.1
    - run: sudo npm install -g markdown-link-check
    - uses: pre-commit/action@v2.0.0
      env:
        SKIP:  no-commit-to-branch
